# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97c30d7f9645eda60cf136d7884855643765bc79c5c956d63cfb05334e2e30db686650c2da456d43191cdae5077d126cd09810f76653cf57f82c901fdb82c5fc

test:
  secret_key_base: cbaa4abd6b69217a7e9ff54c288e4e8c24cedc5662aaeb0772cc543b515630fea8d0bc294c232b35543f80be007b2505f7b498c79398bdc4a250a2fb71fe74dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
